steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    dir: 'integration-gateway'
    id: 'install-dependencies'

  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'integration-gateway'
    id: 'build'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/jira-integration-personal:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/jira-integration-personal:latest',
      '--build-arg', 'JIRA_USER=${_JIRA_USER}',
      'integration-gateway'
    ]
    id: 'build-docker-image'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jira-integration-personal:$COMMIT_SHA']
    id: 'push-docker-image-commit'
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jira-integration-personal:latest']
    id: 'push-docker-image-latest'
    
  # Deploy to Cloud Run (staging)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}-personal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jira-integration-personal:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'JIRA_USER=${_JIRA_USER},GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=staging'
    id: 'deploy-cloud-run'
    
  # Deploy Jira webhook handler Cloud Function (personal)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'jira-webhook-handler-personal'
      - '--gen2'
      - '--runtime'
      - 'nodejs18'
      - '--trigger-http'
      - '--source'
      - 'integration-gateway'
      - '--entry-point'
      - 'handleJiraWebhook'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'JIRA_USER=${_JIRA_USER},GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=staging'
    id: 'deploy-webhook-function'

# Store the Docker image in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/jira-integration-personal:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/jira-integration-personal:latest'
  
# Substitution variables
substitutions:
  _REGION: 'us-west1'
  _SERVICE_NAME: 'jira-integration'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '5'
  _JIRA_USER: 'C2100-PCR'
  
# Define options
options:
  logging: CLOUD_LOGGING_ONLY