packages:
  - "academy/*"
  - "wing/*"
  - "vls/*"
  - "e-commerce/*"
  - "backend/*"
  - "core-protocols/*"
  - "integration/*"
  - "data/*"
  - "aixtiv-cli"
  - "integration-gateway"
  - "godaddy-cli"
  - "domain-management"
  - "aixtiv-symphony-opus1.0.1"
  - "aixtiv-push"
  - "Aixtiv-Symphony"
  - "functions"
  - "my-academy"
  - "aixtiv-assets-resource"
